# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(863, 887)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Dropbox/work/python/lastify/github/lastify icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 861, 731))
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_load = QtGui.QWidget()
        self.tab_load.setToolTip(_fromUtf8(""))
        self.tab_load.setStatusTip(_fromUtf8(""))
        self.tab_load.setWhatsThis(_fromUtf8(""))
        self.tab_load.setObjectName(_fromUtf8("tab_load"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_load)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 851, 137))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lab_limit_charts_track = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_limit_charts_track.setObjectName(_fromUtf8("lab_limit_charts_track"))
        self.gridLayout.addWidget(self.lab_limit_charts_track, 2, 1, 1, 1)
        self.lab_limit_similar_artist = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_limit_similar_artist.setObjectName(_fromUtf8("lab_limit_similar_artist"))
        self.gridLayout.addWidget(self.lab_limit_similar_artist, 0, 5, 1, 1)
        self.lab_rec_similar_artist = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_rec_similar_artist.setObjectName(_fromUtf8("lab_rec_similar_artist"))
        self.gridLayout.addWidget(self.lab_rec_similar_artist, 0, 7, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.lab_rec_charts_artist = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_rec_charts_artist.setObjectName(_fromUtf8("lab_rec_charts_artist"))
        self.gridLayout.addWidget(self.lab_rec_charts_artist, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 8, 1, 1)
        self.lab_limit_charts_artist = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_limit_charts_artist.setObjectName(_fromUtf8("lab_limit_charts_artist"))
        self.gridLayout.addWidget(self.lab_limit_charts_artist, 1, 1, 1, 1)
        self.lab_limit_similar_track = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_limit_similar_track.setObjectName(_fromUtf8("lab_limit_similar_track"))
        self.gridLayout.addWidget(self.lab_limit_similar_track, 1, 5, 1, 1)
        self.lab_rec_charts_track = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_rec_charts_track.setObjectName(_fromUtf8("lab_rec_charts_track"))
        self.gridLayout.addWidget(self.lab_rec_charts_track, 2, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.lab_user_name = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_user_name.setObjectName(_fromUtf8("lab_user_name"))
        self.gridLayout.addWidget(self.lab_user_name, 0, 1, 1, 1)
        self.lab_limit_topalbums = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_limit_topalbums.setObjectName(_fromUtf8("lab_limit_topalbums"))
        self.gridLayout.addWidget(self.lab_limit_topalbums, 3, 5, 1, 1)
        self.lab_limit_toptracks = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_limit_toptracks.setObjectName(_fromUtf8("lab_limit_toptracks"))
        self.gridLayout.addWidget(self.lab_limit_toptracks, 2, 5, 1, 1)
        self.lab_rec_similar_track = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_rec_similar_track.setObjectName(_fromUtf8("lab_rec_similar_track"))
        self.gridLayout.addWidget(self.lab_rec_similar_track, 1, 7, 1, 1)
        self.lab_rec_toptracks = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_rec_toptracks.setObjectName(_fromUtf8("lab_rec_toptracks"))
        self.gridLayout.addWidget(self.lab_rec_toptracks, 2, 7, 1, 1)
        self.in_txt_user = QtGui.QLineEdit(self.gridLayoutWidget)
        self.in_txt_user.setObjectName(_fromUtf8("in_txt_user"))
        self.gridLayout.addWidget(self.in_txt_user, 0, 2, 1, 1)
        self.lab_limit_chart_album = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_limit_chart_album.setObjectName(_fromUtf8("lab_limit_chart_album"))
        self.gridLayout.addWidget(self.lab_limit_chart_album, 3, 1, 1, 1)
        self.lab_rec_charts_album = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_rec_charts_album.setObjectName(_fromUtf8("lab_rec_charts_album"))
        self.gridLayout.addWidget(self.lab_rec_charts_album, 3, 3, 1, 1)
        self.lab_rec_topalbums = QtGui.QLabel(self.gridLayoutWidget)
        self.lab_rec_topalbums.setObjectName(_fromUtf8("lab_rec_topalbums"))
        self.gridLayout.addWidget(self.lab_rec_topalbums, 3, 7, 1, 1)
        self.in_box_limit_charts_artist = QtGui.QSpinBox(self.gridLayoutWidget)
        self.in_box_limit_charts_artist.setMaximum(1000)
        self.in_box_limit_charts_artist.setProperty("value", 50)
        self.in_box_limit_charts_artist.setObjectName(_fromUtf8("in_box_limit_charts_artist"))
        self.gridLayout.addWidget(self.in_box_limit_charts_artist, 1, 2, 1, 1)
        self.in_box_limit_charts_track = QtGui.QSpinBox(self.gridLayoutWidget)
        self.in_box_limit_charts_track.setMaximum(5000)
        self.in_box_limit_charts_track.setProperty("value", 100)
        self.in_box_limit_charts_track.setObjectName(_fromUtf8("in_box_limit_charts_track"))
        self.gridLayout.addWidget(self.in_box_limit_charts_track, 2, 2, 1, 1)
        self.in_box_limit_charts_album = QtGui.QSpinBox(self.gridLayoutWidget)
        self.in_box_limit_charts_album.setMaximum(1000)
        self.in_box_limit_charts_album.setProperty("value", 50)
        self.in_box_limit_charts_album.setObjectName(_fromUtf8("in_box_limit_charts_album"))
        self.gridLayout.addWidget(self.in_box_limit_charts_album, 3, 2, 1, 1)
        self.in_box_limit_similar_artist = QtGui.QSpinBox(self.gridLayoutWidget)
        self.in_box_limit_similar_artist.setMaximum(25)
        self.in_box_limit_similar_artist.setProperty("value", 5)
        self.in_box_limit_similar_artist.setObjectName(_fromUtf8("in_box_limit_similar_artist"))
        self.gridLayout.addWidget(self.in_box_limit_similar_artist, 0, 6, 1, 1)
        self.in_box_limit_similar_track = QtGui.QSpinBox(self.gridLayoutWidget)
        self.in_box_limit_similar_track.setMaximum(25)
        self.in_box_limit_similar_track.setProperty("value", 5)
        self.in_box_limit_similar_track.setObjectName(_fromUtf8("in_box_limit_similar_track"))
        self.gridLayout.addWidget(self.in_box_limit_similar_track, 1, 6, 1, 1)
        self.in_box_limit_toptracks = QtGui.QSpinBox(self.gridLayoutWidget)
        self.in_box_limit_toptracks.setMaximum(25)
        self.in_box_limit_toptracks.setProperty("value", 10)
        self.in_box_limit_toptracks.setObjectName(_fromUtf8("in_box_limit_toptracks"))
        self.gridLayout.addWidget(self.in_box_limit_toptracks, 2, 6, 1, 1)
        self.in_box_limit_topalbums = QtGui.QSpinBox(self.gridLayoutWidget)
        self.in_box_limit_topalbums.setMaximum(25)
        self.in_box_limit_topalbums.setProperty("value", 3)
        self.in_box_limit_topalbums.setObjectName(_fromUtf8("in_box_limit_topalbums"))
        self.gridLayout.addWidget(self.in_box_limit_topalbums, 3, 6, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_load)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 140, 851, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btn_load = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_load.setObjectName(_fromUtf8("btn_load"))
        self.horizontalLayout.addWidget(self.btn_load)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_load)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 841, 373))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lab_thr_status_toptags_artist = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_toptags_artist.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_toptags_artist.setObjectName(_fromUtf8("lab_thr_status_toptags_artist"))
        self.gridLayout_2.addWidget(self.lab_thr_status_toptags_artist, 4, 2, 1, 1)
        self.lab_thr_status_topalbums = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_topalbums.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_topalbums.setObjectName(_fromUtf8("lab_thr_status_topalbums"))
        self.gridLayout_2.addWidget(self.lab_thr_status_topalbums, 3, 2, 1, 1)
        self.bar_toptags_artist = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_toptags_artist.setProperty("value", 0)
        self.bar_toptags_artist.setTextVisible(False)
        self.bar_toptags_artist.setObjectName(_fromUtf8("bar_toptags_artist"))
        self.gridLayout_2.addWidget(self.bar_toptags_artist, 4, 1, 1, 1)
        self.lab_thr_status_toptags_album = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_toptags_album.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_toptags_album.setObjectName(_fromUtf8("lab_thr_status_toptags_album"))
        self.gridLayout_2.addWidget(self.lab_thr_status_toptags_album, 6, 2, 1, 1)
        self.lab_thr_status_toptracks = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_toptracks.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_toptracks.setObjectName(_fromUtf8("lab_thr_status_toptracks"))
        self.gridLayout_2.addWidget(self.lab_thr_status_toptracks, 2, 2, 1, 1)
        self.lab_thr_toptracks = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_toptracks.setObjectName(_fromUtf8("lab_thr_toptracks"))
        self.gridLayout_2.addWidget(self.lab_thr_toptracks, 2, 0, 1, 1)
        self.lab_thr_topalbums = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_topalbums.setObjectName(_fromUtf8("lab_thr_topalbums"))
        self.gridLayout_2.addWidget(self.lab_thr_topalbums, 3, 0, 1, 1)
        self.lab_thr_status_toptags_track = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_toptags_track.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_toptags_track.setObjectName(_fromUtf8("lab_thr_status_toptags_track"))
        self.gridLayout_2.addWidget(self.lab_thr_status_toptags_track, 5, 2, 1, 1)
        self.lab_thr_status_mbinfo = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_mbinfo.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_mbinfo.setObjectName(_fromUtf8("lab_thr_status_mbinfo"))
        self.gridLayout_2.addWidget(self.lab_thr_status_mbinfo, 7, 2, 1, 1)
        self.lab_thr_toptags_track = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_toptags_track.setObjectName(_fromUtf8("lab_thr_toptags_track"))
        self.gridLayout_2.addWidget(self.lab_thr_toptags_track, 5, 0, 1, 1)
        self.lab_thr_spotifyID_track = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_spotifyID_track.setObjectName(_fromUtf8("lab_thr_spotifyID_track"))
        self.gridLayout_2.addWidget(self.lab_thr_spotifyID_track, 8, 0, 1, 1)
        self.lab_thr_status_spotifyID_album = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_spotifyID_album.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_spotifyID_album.setObjectName(_fromUtf8("lab_thr_status_spotifyID_album"))
        self.gridLayout_2.addWidget(self.lab_thr_status_spotifyID_album, 9, 2, 1, 1)
        self.lab_thr_spotifyID_album = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_spotifyID_album.setObjectName(_fromUtf8("lab_thr_spotifyID_album"))
        self.gridLayout_2.addWidget(self.lab_thr_spotifyID_album, 9, 0, 1, 1)
        self.lab_thr_toptags_album = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_toptags_album.setObjectName(_fromUtf8("lab_thr_toptags_album"))
        self.gridLayout_2.addWidget(self.lab_thr_toptags_album, 6, 0, 1, 1)
        self.lab_thr_similar_track = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_similar_track.setObjectName(_fromUtf8("lab_thr_similar_track"))
        self.gridLayout_2.addWidget(self.lab_thr_similar_track, 1, 0, 1, 1)
        self.lab_thr_status_spotifyID_track = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_spotifyID_track.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_spotifyID_track.setObjectName(_fromUtf8("lab_thr_status_spotifyID_track"))
        self.gridLayout_2.addWidget(self.lab_thr_status_spotifyID_track, 8, 2, 1, 1)
        self.lab_thr_status_similar_track = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_similar_track.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_similar_track.setObjectName(_fromUtf8("lab_thr_status_similar_track"))
        self.gridLayout_2.addWidget(self.lab_thr_status_similar_track, 1, 2, 1, 1)
        self.bar_similar_track = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_similar_track.setProperty("value", 0)
        self.bar_similar_track.setTextVisible(False)
        self.bar_similar_track.setObjectName(_fromUtf8("bar_similar_track"))
        self.gridLayout_2.addWidget(self.bar_similar_track, 1, 1, 1, 1)
        self.lab_thr_mbinfo = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_mbinfo.setObjectName(_fromUtf8("lab_thr_mbinfo"))
        self.gridLayout_2.addWidget(self.lab_thr_mbinfo, 7, 0, 1, 1)
        self.bar_toptracks = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_toptracks.setProperty("value", 0)
        self.bar_toptracks.setTextVisible(False)
        self.bar_toptracks.setObjectName(_fromUtf8("bar_toptracks"))
        self.gridLayout_2.addWidget(self.bar_toptracks, 2, 1, 1, 1)
        self.bar_toptags_album = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_toptags_album.setProperty("value", 0)
        self.bar_toptags_album.setTextVisible(False)
        self.bar_toptags_album.setObjectName(_fromUtf8("bar_toptags_album"))
        self.gridLayout_2.addWidget(self.bar_toptags_album, 6, 1, 1, 1)
        self.lab_thr_status_similar_artist = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_status_similar_artist.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_thr_status_similar_artist.setObjectName(_fromUtf8("lab_thr_status_similar_artist"))
        self.gridLayout_2.addWidget(self.lab_thr_status_similar_artist, 0, 2, 1, 1)
        self.bar_spotifyID_track = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_spotifyID_track.setProperty("value", 0)
        self.bar_spotifyID_track.setTextVisible(False)
        self.bar_spotifyID_track.setObjectName(_fromUtf8("bar_spotifyID_track"))
        self.gridLayout_2.addWidget(self.bar_spotifyID_track, 8, 1, 1, 1)
        self.bar_topalbums = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_topalbums.setProperty("value", 0)
        self.bar_topalbums.setTextVisible(False)
        self.bar_topalbums.setObjectName(_fromUtf8("bar_topalbums"))
        self.gridLayout_2.addWidget(self.bar_topalbums, 3, 1, 1, 1)
        self.lab_thr_similar_artist = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_similar_artist.setObjectName(_fromUtf8("lab_thr_similar_artist"))
        self.gridLayout_2.addWidget(self.lab_thr_similar_artist, 0, 0, 1, 1)
        self.bar_similar_artist = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_similar_artist.setProperty("value", 0)
        self.bar_similar_artist.setTextVisible(False)
        self.bar_similar_artist.setObjectName(_fromUtf8("bar_similar_artist"))
        self.gridLayout_2.addWidget(self.bar_similar_artist, 0, 1, 1, 1)
        self.lab_thr_toptags_artist = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_thr_toptags_artist.setObjectName(_fromUtf8("lab_thr_toptags_artist"))
        self.gridLayout_2.addWidget(self.lab_thr_toptags_artist, 4, 0, 1, 1)
        self.bar_toptags_track = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_toptags_track.setProperty("value", 0)
        self.bar_toptags_track.setTextVisible(False)
        self.bar_toptags_track.setObjectName(_fromUtf8("bar_toptags_track"))
        self.gridLayout_2.addWidget(self.bar_toptags_track, 5, 1, 1, 1)
        self.bar_mbinfo = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_mbinfo.setProperty("value", 0)
        self.bar_mbinfo.setTextVisible(False)
        self.bar_mbinfo.setObjectName(_fromUtf8("bar_mbinfo"))
        self.gridLayout_2.addWidget(self.bar_mbinfo, 7, 1, 1, 1)
        self.bar_spotifyID_album = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.bar_spotifyID_album.setProperty("value", 0)
        self.bar_spotifyID_album.setTextVisible(False)
        self.bar_spotifyID_album.setObjectName(_fromUtf8("bar_spotifyID_album"))
        self.gridLayout_2.addWidget(self.bar_spotifyID_album, 9, 1, 1, 1)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tab_load)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 590, 841, 93))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bar_call_lastfm = QtGui.QProgressBar(self.horizontalLayoutWidget_3)
        self.bar_call_lastfm.setMaximum(1500)
        self.bar_call_lastfm.setProperty("value", 0)
        self.bar_call_lastfm.setTextVisible(False)
        self.bar_call_lastfm.setOrientation(QtCore.Qt.Vertical)
        self.bar_call_lastfm.setObjectName(_fromUtf8("bar_call_lastfm"))
        self.horizontalLayout_3.addWidget(self.bar_call_lastfm)
        self.lab_lastfm = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.lab_lastfm.setWordWrap(True)
        self.lab_lastfm.setObjectName(_fromUtf8("lab_lastfm"))
        self.horizontalLayout_3.addWidget(self.lab_lastfm)
        self.bar_call_spotify = QtGui.QProgressBar(self.horizontalLayoutWidget_3)
        self.bar_call_spotify.setMaximum(1500)
        self.bar_call_spotify.setProperty("value", 0)
        self.bar_call_spotify.setTextVisible(False)
        self.bar_call_spotify.setOrientation(QtCore.Qt.Vertical)
        self.bar_call_spotify.setObjectName(_fromUtf8("bar_call_spotify"))
        self.horizontalLayout_3.addWidget(self.bar_call_spotify)
        self.lab_spotify = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.lab_spotify.setWordWrap(True)
        self.lab_spotify.setObjectName(_fromUtf8("lab_spotify"))
        self.horizontalLayout_3.addWidget(self.lab_spotify)
        self.bar_call_mbinfo = QtGui.QProgressBar(self.horizontalLayoutWidget_3)
        self.bar_call_mbinfo.setMaximum(20)
        self.bar_call_mbinfo.setProperty("value", 0)
        self.bar_call_mbinfo.setTextVisible(False)
        self.bar_call_mbinfo.setOrientation(QtCore.Qt.Vertical)
        self.bar_call_mbinfo.setObjectName(_fromUtf8("bar_call_mbinfo"))
        self.horizontalLayout_3.addWidget(self.bar_call_mbinfo)
        self.lab_mbinfo = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.lab_mbinfo.setWordWrap(True)
        self.lab_mbinfo.setObjectName(_fromUtf8("lab_mbinfo"))
        self.horizontalLayout_3.addWidget(self.lab_mbinfo)
        self.tabWidget.addTab(self.tab_load, _fromUtf8(""))
        self.tab_filter = QtGui.QWidget()
        self.tab_filter.setObjectName(_fromUtf8("tab_filter"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_filter)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 531))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.verticalLayout.addWidget(self.comboBox_2)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_filter)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(330, 50, 521, 54))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.select_tag = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.select_tag.setMinimumSize(QtCore.QSize(200, 22))
        self.select_tag.setMaxVisibleItems(100)
        self.select_tag.setObjectName(_fromUtf8("select_tag"))
        self.gridLayout_3.addWidget(self.select_tag, 2, 1, 1, 1)
        self.lab_tag = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lab_tag.setObjectName(_fromUtf8("lab_tag"))
        self.gridLayout_3.addWidget(self.lab_tag, 1, 1, 1, 1)
        self.select_tag_category = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.select_tag_category.setMinimumSize(QtCore.QSize(0, 22))
        self.select_tag_category.setObjectName(_fromUtf8("select_tag_category"))
        self.gridLayout_3.addWidget(self.select_tag_category, 2, 0, 1, 1)
        self.lab_tag_type = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lab_tag_type.setObjectName(_fromUtf8("lab_tag_type"))
        self.gridLayout_3.addWidget(self.lab_tag_type, 1, 0, 1, 1)
        self.in_box_tagscore = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.in_box_tagscore.setMinimumSize(QtCore.QSize(0, 22))
        self.in_box_tagscore.setMaximum(100)
        self.in_box_tagscore.setProperty("value", 0)
        self.in_box_tagscore.setObjectName(_fromUtf8("in_box_tagscore"))
        self.gridLayout_3.addWidget(self.in_box_tagscore, 2, 2, 1, 1)
        self.btn_add_filter_tag = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.btn_add_filter_tag.setMinimumSize(QtCore.QSize(93, 22))
        self.btn_add_filter_tag.setMaximumSize(QtCore.QSize(93, 16777215))
        self.btn_add_filter_tag.setObjectName(_fromUtf8("btn_add_filter_tag"))
        self.gridLayout_3.addWidget(self.btn_add_filter_tag, 2, 3, 1, 1)
        self.lab_tag_score = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lab_tag_score.setObjectName(_fromUtf8("lab_tag_score"))
        self.gridLayout_3.addWidget(self.lab_tag_score, 1, 2, 1, 1)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab_filter)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(330, 0, 230, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.select_list_category = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.select_list_category.setObjectName(_fromUtf8("select_list_category"))
        self.horizontalLayout_2.addWidget(self.select_list_category)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab_filter)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(330, 120, 521, 148))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lab_plays_user = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lab_plays_user.setObjectName(_fromUtf8("lab_plays_user"))
        self.gridLayout_4.addWidget(self.lab_plays_user, 0, 0, 1, 1)
        self.select_date_category = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.select_date_category.setObjectName(_fromUtf8("select_date_category"))
        self.gridLayout_4.addWidget(self.select_date_category, 4, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 2, 2, 1, 1)
        self.btn_add_filter_plays = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.btn_add_filter_plays.setMinimumSize(QtCore.QSize(93, 0))
        self.btn_add_filter_plays.setMaximumSize(QtCore.QSize(93, 16777215))
        self.btn_add_filter_plays.setObjectName(_fromUtf8("btn_add_filter_plays"))
        self.gridLayout_4.addWidget(self.btn_add_filter_plays, 1, 5, 1, 1)
        self.select_plays_category = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.select_plays_category.setObjectName(_fromUtf8("select_plays_category"))
        self.gridLayout_4.addWidget(self.select_plays_category, 1, 1, 1, 1)
        self.lab_date_category = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lab_date_category.setObjectName(_fromUtf8("lab_date_category"))
        self.gridLayout_4.addWidget(self.lab_date_category, 3, 1, 1, 1)
        self.btn_add_filter_date = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.btn_add_filter_date.setMinimumSize(QtCore.QSize(93, 0))
        self.btn_add_filter_date.setMaximumSize(QtCore.QSize(93, 16777215))
        self.btn_add_filter_date.setObjectName(_fromUtf8("btn_add_filter_date"))
        self.gridLayout_4.addWidget(self.btn_add_filter_date, 4, 5, 1, 1)
        self.lab_plays_type = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lab_plays_type.setObjectName(_fromUtf8("lab_plays_type"))
        self.gridLayout_4.addWidget(self.lab_plays_type, 0, 1, 1, 1)
        self.in_box_plays_min = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.in_box_plays_min.setMaximum(9999999)
        self.in_box_plays_min.setObjectName(_fromUtf8("in_box_plays_min"))
        self.gridLayout_4.addWidget(self.in_box_plays_min, 1, 2, 1, 1)
        self.lab_plays_min = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lab_plays_min.setObjectName(_fromUtf8("lab_plays_min"))
        self.gridLayout_4.addWidget(self.lab_plays_min, 0, 2, 1, 1)
        self.in_box_date_min = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.in_box_date_min.setMinimum(1850)
        self.in_box_date_min.setMaximum(2050)
        self.in_box_date_min.setProperty("value", 2000)
        self.in_box_date_min.setObjectName(_fromUtf8("in_box_date_min"))
        self.gridLayout_4.addWidget(self.in_box_date_min, 4, 2, 1, 1)
        self.lab_date_max = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lab_date_max.setObjectName(_fromUtf8("lab_date_max"))
        self.gridLayout_4.addWidget(self.lab_date_max, 3, 3, 1, 1)
        self.lab_date_min = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lab_date_min.setObjectName(_fromUtf8("lab_date_min"))
        self.gridLayout_4.addWidget(self.lab_date_min, 3, 2, 1, 1)
        self.in_box_date_max = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.in_box_date_max.setMinimum(1850)
        self.in_box_date_max.setMaximum(2050)
        self.in_box_date_max.setProperty("value", 2016)
        self.in_box_date_max.setObjectName(_fromUtf8("in_box_date_max"))
        self.gridLayout_4.addWidget(self.in_box_date_max, 4, 3, 1, 1)
        self.in_box_plays_max = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.in_box_plays_max.setMaximum(9999999)
        self.in_box_plays_max.setObjectName(_fromUtf8("in_box_plays_max"))
        self.gridLayout_4.addWidget(self.in_box_plays_max, 1, 3, 1, 1)
        self.lab_plays_max = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lab_plays_max.setObjectName(_fromUtf8("lab_plays_max"))
        self.gridLayout_4.addWidget(self.lab_plays_max, 0, 3, 1, 1)
        self.select_user = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.select_user.setMaximumSize(QtCore.QSize(78, 16777215))
        self.select_user.setObjectName(_fromUtf8("select_user"))
        self.gridLayout_4.addWidget(self.select_user, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 4, 1, 1)
        self.lab_date_undated = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lab_date_undated.setMaximumSize(QtCore.QSize(78, 16777215))
        self.lab_date_undated.setWordWrap(True)
        self.lab_date_undated.setObjectName(_fromUtf8("lab_date_undated"))
        self.gridLayout_4.addWidget(self.lab_date_undated, 3, 0, 1, 1)
        self.checkbox_date = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkbox_date.setText(_fromUtf8(""))
        self.checkbox_date.setObjectName(_fromUtf8("checkbox_date"))
        self.gridLayout_4.addWidget(self.checkbox_date, 4, 0, 1, 1)
        self.list_filt = QtGui.QListWidget(self.tab_filter)
        self.list_filt.setGeometry(QtCore.QRect(330, 280, 161, 261))
        self.list_filt.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.list_filt.setObjectName(_fromUtf8("list_filt"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_filter)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(520, 280, 229, 80))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btn_del_filter = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btn_del_filter.setMinimumSize(QtCore.QSize(93, 0))
        self.btn_del_filter.setMaximumSize(QtCore.QSize(93, 16777215))
        self.btn_del_filter.setObjectName(_fromUtf8("btn_del_filter"))
        self.gridLayout_5.addWidget(self.btn_del_filter, 0, 0, 1, 1)
        self.lab_title_no_items = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lab_title_no_items.setObjectName(_fromUtf8("lab_title_no_items"))
        self.gridLayout_5.addWidget(self.lab_title_no_items, 1, 0, 1, 1)
        self.lab_no_items = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lab_no_items.setObjectName(_fromUtf8("lab_no_items"))
        self.gridLayout_5.addWidget(self.lab_no_items, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_filter)
        self.label_2.setGeometry(QtCore.QRect(520, 380, 211, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_filter)
        self.label_3.setGeometry(QtCore.QRect(520, 410, 211, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btn_refresh_filtman = QtGui.QPushButton(self.tab_filter)
        self.btn_refresh_filtman.setGeometry(QtCore.QRect(760, 10, 93, 28))
        self.btn_refresh_filtman.setMinimumSize(QtCore.QSize(93, 22))
        self.btn_refresh_filtman.setMaximumSize(QtCore.QSize(93, 16777215))
        self.btn_refresh_filtman.setText(_fromUtf8("refresh"))
        self.btn_refresh_filtman.setObjectName(_fromUtf8("btn_refresh_filtman"))
        self.btn_pass = QtGui.QPushButton(self.tab_filter)
        self.btn_pass.setGeometry(QtCore.QRect(520, 450, 331, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_pass.setFont(font)
        self.btn_pass.setObjectName(_fromUtf8("btn_pass"))
        self.tabWidget.addTab(self.tab_filter, _fromUtf8(""))
        self.tab_write = QtGui.QWidget()
        self.tab_write.setObjectName(_fromUtf8("tab_write"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_write)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 841, 82))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.in_box_limit_items_per_artist = QtGui.QSpinBox(self.gridLayoutWidget_6)
        self.in_box_limit_items_per_artist.setMinimum(1)
        self.in_box_limit_items_per_artist.setMaximum(100)
        self.in_box_limit_items_per_artist.setObjectName(_fromUtf8("in_box_limit_items_per_artist"))
        self.gridLayout_6.addWidget(self.in_box_limit_items_per_artist, 1, 1, 1, 1)
        self.in_txt_list_name = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.in_txt_list_name.setObjectName(_fromUtf8("in_txt_list_name"))
        self.gridLayout_6.addWidget(self.in_txt_list_name, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.select_list_sortby = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.select_list_sortby.setObjectName(_fromUtf8("select_list_sortby"))
        self.gridLayout_6.addWidget(self.select_list_sortby, 0, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 4, 1, 1)
        self.btn_wr_list = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.btn_wr_list.setObjectName(_fromUtf8("btn_wr_list"))
        self.gridLayout_6.addWidget(self.btn_wr_list, 0, 6, 1, 1)
        self.select_list_rankby = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.select_list_rankby.setObjectName(_fromUtf8("select_list_rankby"))
        self.gridLayout_6.addWidget(self.select_list_rankby, 1, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 1, 4, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 0, 2, 1, 1)
        self.btn_apply_artist_limit = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.btn_apply_artist_limit.setObjectName(_fromUtf8("btn_apply_artist_limit"))
        self.gridLayout_6.addWidget(self.btn_apply_artist_limit, 1, 6, 1, 1)
        self.select_list_sortby_asc = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.select_list_sortby_asc.setObjectName(_fromUtf8("select_list_sortby_asc"))
        self.gridLayout_6.addWidget(self.select_list_sortby_asc, 0, 3, 1, 1)
        self.select_list_rankby_asc = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.select_list_rankby_asc.setObjectName(_fromUtf8("select_list_rankby_asc"))
        self.gridLayout_6.addWidget(self.select_list_rankby_asc, 1, 3, 1, 1)
        self.tableview = QtGui.QTableView(self.tab_write)
        self.tableview.setGeometry(QtCore.QRect(10, 100, 841, 601))
        self.tableview.setObjectName(_fromUtf8("tableview"))
        self.tabWidget.addTab(self.tab_write, _fromUtf8(""))
        self.tab_stats = QtGui.QWidget()
        self.tab_stats.setObjectName(_fromUtf8("tab_stats"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab_stats)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 791, 521))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget.addTab(self.tab_stats, _fromUtf8(""))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 740, 861, 91))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lab_status_dblock = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lab_status_dblock.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_status_dblock.setObjectName(_fromUtf8("lab_status_dblock"))
        self.verticalLayout_2.addWidget(self.lab_status_dblock)
        self.lab_status_filter = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lab_status_filter.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_status_filter.setObjectName(_fromUtf8("lab_status_filter"))
        self.verticalLayout_2.addWidget(self.lab_status_filter)
        self.lab_status_writer = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lab_status_writer.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_status_writer.setObjectName(_fromUtf8("lab_status_writer"))
        self.verticalLayout_2.addWidget(self.lab_status_writer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "lastify", None))
        self.lab_limit_charts_track.setText(_translate("MainWindow", "track charts limit: ", None))
        self.lab_limit_similar_artist.setText(_translate("MainWindow", "similar artists limit: ", None))
        self.lab_rec_similar_artist.setText(_translate("MainWindow", "(0-25)", None))
        self.lab_rec_charts_artist.setText(_translate("MainWindow", "(0-1000)", None))
        self.lab_limit_charts_artist.setText(_translate("MainWindow", "artist charts limit: ", None))
        self.lab_limit_similar_track.setText(_translate("MainWindow", "similar tracks limit: ", None))
        self.lab_rec_charts_track.setText(_translate("MainWindow", "(0-5000)", None))
        self.lab_user_name.setText(_translate("MainWindow", "lastfm user name:", None))
        self.lab_limit_topalbums.setText(_translate("MainWindow", "topalbums/artist limit:", None))
        self.lab_limit_toptracks.setText(_translate("MainWindow", "toptracks/artist limit:", None))
        self.lab_rec_similar_track.setText(_translate("MainWindow", "(0-25)", None))
        self.lab_rec_toptracks.setText(_translate("MainWindow", "(0-25)", None))
        self.in_txt_user.setText(_translate("MainWindow", "erblast", None))
        self.lab_limit_chart_album.setText(_translate("MainWindow", "album charts limit: ", None))
        self.lab_rec_charts_album.setText(_translate("MainWindow", "(0-1000)", None))
        self.lab_rec_topalbums.setText(_translate("MainWindow", "(0-25)", None))
        self.btn_load.setText(_translate("MainWindow", "Start Loading", None))
        self.lab_thr_status_toptags_artist.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_status_topalbums.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_status_toptags_album.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_status_toptracks.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_toptracks.setText(_translate("MainWindow", " toptracks/ artist", None))
        self.lab_thr_topalbums.setText(_translate("MainWindow", " topalbums/ artist", None))
        self.lab_thr_status_toptags_track.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_status_mbinfo.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_toptags_track.setText(_translate("MainWindow", " toptags/ track", None))
        self.lab_thr_spotifyID_track.setText(_translate("MainWindow", " spotifyID/ track", None))
        self.lab_thr_status_spotifyID_album.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_spotifyID_album.setText(_translate("MainWindow", " spotifyID/ album", None))
        self.lab_thr_toptags_album.setText(_translate("MainWindow", " toptags/ album", None))
        self.lab_thr_similar_track.setText(_translate("MainWindow", " similar tracks/ track", None))
        self.lab_thr_status_spotifyID_track.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_status_similar_track.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_mbinfo.setText(_translate("MainWindow", " release dates/ album", None))
        self.lab_thr_status_similar_artist.setText(_translate("MainWindow", "inactive", None))
        self.lab_thr_similar_artist.setText(_translate("MainWindow", " similar artists/ artist", None))
        self.lab_thr_toptags_artist.setText(_translate("MainWindow", " toptags/ artist", None))
        self.lab_lastfm.setText(_translate("MainWindow", "inactive", None))
        self.lab_spotify.setText(_translate("MainWindow", "inactive", None))
        self.lab_mbinfo.setText(_translate("MainWindow", "inactive", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_load), _translate("MainWindow", "Load", None))
        self.select_tag.setToolTip(_translate("MainWindow", "<html><head/><body><p>values denote number of items associated with tag with tagscore &gt;= 0</p></body></html>", None))
        self.lab_tag.setText(_translate("MainWindow", "tag", None))
        self.lab_tag_type.setText(_translate("MainWindow", "category", None))
        self.in_box_tagscore.setToolTip(_translate("MainWindow", "<html><head/><body><p>score 0-100 for the required association with the tag</p></body></html>", None))
        self.btn_add_filter_tag.setText(_translate("MainWindow", "add tag filter", None))
        self.lab_tag_score.setText(_translate("MainWindow", "min tagscore", None))
        self.label.setText(_translate("MainWindow", "Playlist category:", None))
        self.select_list_category.setToolTip(_translate("MainWindow", "<html><head/><body><p>set playlist category</p></body></html>", None))
        self.lab_plays_user.setText(_translate("MainWindow", "user", None))
        self.select_date_category.setToolTip(_translate("MainWindow", "<html><head/><body><p>dates for artist is the year of the release with the greatest number of total plays</p></body></html>", None))
        self.btn_add_filter_plays.setText(_translate("MainWindow", "add plays filter", None))
        self.lab_date_category.setText(_translate("MainWindow", "category", None))
        self.btn_add_filter_date.setText(_translate("MainWindow", "add date filter", None))
        self.lab_plays_type.setText(_translate("MainWindow", "category", None))
        self.lab_plays_min.setText(_translate("MainWindow", "plays min", None))
        self.lab_date_max.setText(_translate("MainWindow", "date max", None))
        self.lab_date_min.setText(_translate("MainWindow", "date min", None))
        self.in_box_plays_max.setToolTip(_translate("MainWindow", "<html><head/><body><p>if left at zero no maximum is set</p></body></html>", None))
        self.lab_plays_max.setText(_translate("MainWindow", "plays max", None))
        self.lab_date_undated.setText(_translate("MainWindow", "include undated", None))
        self.checkbox_date.setToolTip(_translate("MainWindow", "<html><head/><body><p>lots of items in database have no date association</p></body></html>", None))
        self.btn_del_filter.setText(_translate("MainWindow", "delete filter", None))
        self.lab_title_no_items.setText(_translate("MainWindow", "Number of items in playlist: ", None))
        self.lab_no_items.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "Hint: try to use less than 1000 items! ", None))
        self.label_3.setText(_translate("MainWindow", "Maximum 5000", None))
        self.btn_refresh_filtman.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Warning</span> refreshes filter manager, can take long to execute</p></body></html>", None))
        self.btn_pass.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">uses user name entered in load tab </span></p><p><span style=\" font-weight:400;\">Caution takes long for bigger databases</span></p></body></html>", None))
        self.btn_pass.setText(_translate("MainWindow", ">> Pass filtered items to Writer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_filter), _translate("MainWindow", "Filter", None))
        self.label_6.setText(_translate("MainWindow", "playlist name:", None))
        self.label_4.setText(_translate("MainWindow", "limit items/ artist", None))
        self.label_7.setText(_translate("MainWindow", "sort by:", None))
        self.btn_wr_list.setText(_translate("MainWindow", "Write Playlist", None))
        self.label_5.setText(_translate("MainWindow", "rank by", None))
        self.btn_apply_artist_limit.setToolTip(_translate("MainWindow", "<html><head/><body><p>groups list per artist ranks according to setting and selects the top</p></body></html>", None))
        self.btn_apply_artist_limit.setText(_translate("MainWindow", "Apply limit", None))
        self.tableview.setToolTip(_translate("MainWindow", "<html><head/><body><p>only displays 257 items</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_write), _translate("MainWindow", "Writer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stats), _translate("MainWindow", "Stats", None))
        self.lab_status_dblock.setText(_translate("MainWindow", "lockowner", None))
        self.lab_status_filter.setText(_translate("MainWindow", "filter status", None))
        self.lab_status_writer.setText(_translate("MainWindow", "writer status", None))

